###
// 카카오 로그인
GET http://localhost:3000/api/auth/kakao/callback

###
GET http://14.34.139.253:3000/api/auth/kakao/callback


###
///로컬 회원가입(이메일 인증받고 가입하기)
POST http://14.34.139.253:3000/api/auth/local
Content-Type: application/json

{
  "email" : "rtg1014@naver.com",
  "password" : "aaaa123!",
  "confirmPassword" : "aaaa123!",
  "userName" : "테스터"
}



###
/// 인증번호 입력창###
///로컬 회원가입(이메일 인증받고 가입하기)
POST http://localhost:3000/api/auth/verifyNumberForNew
Content-Type: application/json

{
  "email" : "rtg1014@naver.com",
  "password" : "aaaa123!",
  "userName" : "테스터",
  "authNumber" : 136086
}

###
POST http://localhost:3000/api/auth
Content-Type: application/json

{
  "email" : "rtg1014@naver.com",
 "password" : "aaaa123!"
}

###
POST http://14.34.139.253:3000/api/schedule
Content-Type: application/json

{
"image" : ,
"companyName" : ,
"title" :,
"sticker" :,
"date" : "2022-07-09 02:10",
"place" : ,
"memo" : ,
}




//--------------------------------------------------------------------------------------------------
//--------------------------------------------------------------------------------------------------

###
GET http://localhost:3000/api/lobby

http://3.39.161.93:3000/api/login

###
GET http://localhost:3000/api/page/2

###
GET http://localhost:3000/api/mypage

###
POST http://3.39.161.93:3000/api/signup
Content-Type: application/json

{
  "email":"ksh1@naver.com",
  "password":"123123",
  "confirmPassword": "123123",
  "userName": "성현킴"
}




###
//로컬 회원가입
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email":"abcd@naver.com",
  "password":"123123123123123",
  "confirmPassword": "123123123123123",
  "userName": "김성현"
}

###
// 로그인
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email":"fsfsfs1010@naver.com",
    "password":"성현111!!!"
}

###
/// 이메일로 비밀번호 찾기
POST http://localhost:3000/api/send/pw
Content-Type: application/json

{
  "email" : "rtg1014@naver.com"
}




